import assert from 'node:assert/strict';
import test from 'node:test';
import { readPsychologySettingsProjection, projectPsychologySettingsSnapshot, sanitizePsychologySettingsProjectionError, SETTINGS_OPERATIONAL_FIELD_PATHS, SETTINGS_PERSONAL_FIELD_PATHS } from '../api/_lib/psychologySettingsProjection.js';

const scope = Object.freeze({ workspaceId: 'workspace-r83', tenantId: 'tenant-r83', professionalId: 'professional-r83', context: 'PSICOLOGIA' });
const snapshot = () => ({ exists: true, data: () => ({ settings: { professionalProfile: { email: 'private@example.invalid' }, services: [{ name: 'private service' }], locations: [{ address: 'private address' }], agenda: { defaultDurationMinutes: 50, intervalMinutes: 15 } } }) });

test('projeção retorna apenas metadados sanitizados', () => { const result = projectPsychologySettingsSnapshot(snapshot()); assert.deepEqual(result, { ok: true, settingsFound: true, settingsStructureValid: true, servicesPresent: true, servicesCount: 1, locationsPresent: true, locationsCount: 1, agendaDefaultsPresent: true }); assert.equal(JSON.stringify(result).includes('private'), false); });
test('leitura usa uma fieldMask e não usa get bruto', async () => { const calls = []; const db = { collection: path => ({ doc: id => ({ path, id, get: () => { throw new Error('raw get'); } }) }), async getAll(...args) { calls.push(args); return [snapshot()]; } }; const result = await readPsychologySettingsProjection({ db, runtimeScope: scope }); assert.equal(result.ok, true); assert.equal(calls.length, 1); assert.deepEqual(calls[0][1], { fieldMask: SETTINGS_OPERATIONAL_FIELD_PATHS }); assert.equal(SETTINGS_PERSONAL_FIELD_PATHS.some(path => path.includes('email')), true); });
test('escopo incompleto é bloqueado antes da leitura', async () => { let reads = 0; const db = { collection() { reads += 1; throw new Error('must not read'); }, getAll() { reads += 1; throw new Error('must not read'); } }; await assert.rejects(() => readPsychologySettingsProjection({ db, runtimeScope: { context: 'PSICOLOGIA', professionalId: 'professional-r83' } }), error => error.code === 'psychology/settings-projection-scope-unavailable'); assert.equal(reads, 0); });
test('erro da projeção é sanitizado', () => { const result = sanitizePsychologySettingsProjectionError(Object.assign(new Error('sensitive detail'), { code: '7', statusCode: 503 })); assert.equal(result.errorCode, 'psychology/settings-projection-failed'); assert.equal(JSON.stringify(result).includes('sensitive'), false); });
