import assert from 'node:assert/strict';
import { test } from 'node:test';
import { createEmptyPsychologyStore, createPsychologyScope } from '../src/features/psychology-pilot/psychologyDomain';
import {
  createDoctoraliaPreview,
  createDoctoraliaPreviewBundle,
  DOCTORALIA_PREVIEW_SOURCE,
  DOCTORALIA_PREVIEW_HIDDEN_CANCELLED_STORAGE_KEY,
  DOCTORALIA_PREVIEW_STORAGE_KEY,
  formatDoctoraliaAddress,
  getDoctoraliaPreviewSessionsForDate,
  getDoctoraliaPreviewSessionsForPatient,
  getDoctoraliaPreviewSessionsForRange,
  parseDoctoraliaPreviewBundle,
  parseDoctoraliaPreviewHiddenCancelledEventIds,
  serializeDoctoraliaPreviewBundle,
  serializeDoctoraliaPreviewHiddenCancelledEventIds,
} from '../src/features/psychology-import-export/doctoraliaPreview';
import type { DoctoraliaDryRunResult } from '../src/features/psychology-import-export/types';
import type { PsychologyPatient, PsychologyStore } from '../src/features/psychology-pilot/psychologyDomain';
import { deletePsychologyPatientLocally, getPsychologyPatientDeletionAssessment, normalizePsychologyPhone } from '../src/features/psychology-pilot/psychologyPatientDeletion';
import { getPsychologyAgendaScale, psychologyAgendaTimeToMinutes, PSYCHOLOGY_AGENDA_TOTAL_MINUTES } from '../src/features/psychology-pilot/psychologyAgendaScale';
import {
  createPsychologyWeeklyAvailabilityFromLegacy,
  getPsychologyAvailabilityPeriods,
  getPsychologyAvailabilityTimes,
  isPsychologyDateTimeWithinAvailability,
  normalizePsychologySettings,
  normalizePsychologyWeeklyAvailability,
  derivePsychologyAgendaColorTokens,
  hasReadableContrast,
  resolvePsychologyAgendaEventStyle,
} from '../src/features/psychology-pilot/psychologyR2a';
import { getPsychologyAgendaReport } from '../src/features/psychology-pilot/psychologyReports';
import { createPsychologyPeriod } from '../src/features/psychology-pilot/psychologyFinancialLedger';
import { readFileSync } from 'node:fs';

const baseStore = createEmptyPsychologyStore(createPsychologyScope('synthetic-professional'));
const dryRun: DoctoraliaDryRunResult = {
  patientCounts: { total: 3, groupA: 2, groupB: 1, groupC: 1, activeByFutureEvidence: 1, inactiveReview: 2, initiallyImportable: 2, notImportedInitially: 1 },
  appointmentCounts: { totalOriginal: 4, beforeCutoff: 0, atOrAfterCutoff: 4, cancelled: 1, future: 1, historicalAttendanceUnknown: 2, importable: 4 },
  patients: [
    { externalPatientId: 'patient-a', firstName: 'Paciente', lastName: 'Sintetico A', name: 'Paciente Sintetico A', phone: '000000000', email: 'synthetic-a@example.test', birthDate: '1990-01-01', address: { street: 'Rua Fixture', number: '10', city: 'Cidade Teste', state: 'TS' }, demographics: { education: 'Superior' }, status: 'INACTIVE', group: 'A_HISTORY_NON_CANCELLED', migrationReview: { required: true, reason: 'STATUS_NOT_CONFIRMED' }, importable: true, externalReference: { source: 'DOCTORALIA', externalId: 'patient-a' } },
    { externalPatientId: 'patient-b', firstName: 'Paciente', lastName: 'Sintetico B', name: 'Paciente Sintetico B', phone: '000000001', address: {}, demographics: {}, status: 'ACTIVE', group: 'A_HISTORY_NON_CANCELLED', importable: true, externalReference: { source: 'DOCTORALIA', externalId: 'patient-b' } },
  ],
  notImportedPatients: [{ externalPatientId: 'patient-c', name: 'Paciente Sintetico C', reason: 'NO_APPOINTMENTS_FOUND', reviewable: true }],
  appointments: [
    { externalEventId: 'event-unknown', externalScheduleId: 'schedule-unknown', externalPatientId: 'patient-a', agenda: 'Agenda Fixture', service: 'Serviço Fixture', civilDate: '2025-01-02', startTime: '09:00', durationMinutes: 50, sourceStatus: 'Confirmed', status: 'LEGACY_ATTENDANCE_UNKNOWN', modality: 'PRESENCIAL', locationName: 'Local Fixture', importable: true, historicalAttendanceUnknown: true, externalReference: { source: 'DOCTORALIA', externalId: 'event-unknown' } },
    { externalEventId: 'event-cancelled', externalScheduleId: 'schedule-cancelled', externalPatientId: 'patient-a', agenda: 'Agenda Fixture', service: 'Serviço Fixture', civilDate: '2025-01-02', startTime: '10:00', durationMinutes: 50, sourceStatus: 'CanceledByPatient', status: 'CANCELLED', modality: 'PRESENCIAL', locationName: 'Local Fixture', importable: true, historicalAttendanceUnknown: false, externalReference: { source: 'DOCTORALIA', externalId: 'event-cancelled' } },
    { externalEventId: 'event-future', externalScheduleId: 'schedule-future', externalPatientId: 'patient-b', agenda: 'Agenda Fixture', service: 'Teleatendimento Fixture', civilDate: '2026-09-01', startTime: '11:00', durationMinutes: 60, sourceStatus: 'Confirmed', status: 'SCHEDULED', modality: 'ONLINE', importable: true, historicalAttendanceUnknown: false, externalReference: { source: 'DOCTORALIA', externalId: 'event-future' } },
    { externalEventId: 'event-range', externalScheduleId: 'schedule-range', externalPatientId: 'patient-b', agenda: 'Agenda Fixture', service: 'Serviço Fixture', civilDate: '2026-09-03', startTime: '12:00', durationMinutes: 50, sourceStatus: 'Confirmed', status: 'LEGACY_ATTENDANCE_UNKNOWN', modality: 'ONLINE', importable: true, historicalAttendanceUnknown: true, externalReference: { source: 'DOCTORALIA', externalId: 'event-range' } },
  ],
  clinicalBackgrounds: [{ externalPatientId: 'patient-a', medications: 'medicação sintética protegida', source: 'DOCTORALIA', protected: true }],
  locations: [{ name: 'Local Fixture', normalizedKey: 'localfixture', source: 'DOCTORALIA', externalReference: { source: 'DOCTORALIA', externalId: 'location-fixture' } }],
  services: [
    { name: 'Serviço Fixture', normalizedKey: 'servicofixture', source: 'DOCTORALIA', externalReference: { source: 'DOCTORALIA', externalId: 'service-fixture' } },
    { name: 'Teleatendimento Fixture', normalizedKey: 'teleatendimento-fixture', source: 'DOCTORALIA', externalReference: { source: 'DOCTORALIA', externalId: 'service-online' } },
  ],
  ignoredFields: ['comments', 'fiscal fields'],
  writesPerformed: false,
  deletesPerformed: false,
  persisted: false,
  details: ['synthetic fixture'],
};

const payload = { cutoff: '2025-01-01' as const, timezone: 'America/Sao_Paulo' as const, dryRun };

test('R2B3 preview 01 — usa namespace de sessionStorage exclusivo', () => assert.equal(DOCTORALIA_PREVIEW_STORAGE_KEY, 'gestao-clinica:psychology-doctoralia-preview:v1'));
test('R2B3 preview 02 — identifica a origem técnica da prévia', () => assert.equal(createDoctoraliaPreviewBundle(payload, baseStore).source, DOCTORALIA_PREVIEW_SOURCE));
test('R2B3 preview 03 — mantém somente pacientes importáveis na lista normal', () => assert.equal(createDoctoraliaPreviewBundle(payload, baseStore).patients.length, 2));
test('R2B3 preview 04 — mantém Grupo C somente na revisão', () => assert.equal(createDoctoraliaPreviewBundle(payload, baseStore).notImportedPatients.length, 1));
test('R2B3 preview 05 — preserva a proporção ativa/inativa do dry-run', () => { const bundle = createDoctoraliaPreviewBundle(payload, baseStore); assert.equal(bundle.patientCounts.activeByFutureEvidence, 1); assert.equal(bundle.patientCounts.inactiveReview, 2); });
test('R2B3 preview 06 — não grava no store normal ao criar bundle', () => { const before = JSON.stringify(baseStore); createDoctoraliaPreview(payload, baseStore); assert.equal(JSON.stringify(baseStore), before); });
test('R2B3 preview 07 — IDs internos da prévia não são IDs externos', () => { const bundle = createDoctoraliaPreviewBundle(payload, baseStore); assert.equal(bundle.patients[0]?.id.startsWith('doctoralia-preview-patient-'), true); assert.notEqual(bundle.patients[0]?.id, 'patient-a'); });
test('R2B3 preview 08 — conserva referências externas apenas no modelo técnico', () => { const patient = createDoctoraliaPreviewBundle(payload, baseStore).patients[0]; assert.deepEqual(patient?.externalReferences?.[0], { source: 'DOCTORALIA', externalId: 'patient-a', importedAt: patient?.externalReferences?.[0]?.importedAt }); });
test('R2B3 preview 09 — cria índice por data', () => { const bundle = createDoctoraliaPreviewBundle(payload, baseStore); assert.equal(bundle.sessionsByDate['2025-01-02']?.length, 2); });
test('R2B3 preview 10 — cria índice por paciente', () => { const bundle = createDoctoraliaPreviewBundle(payload, baseStore); assert.equal(bundle.sessionsByPatientId[bundle.patients[0]!.id]?.length, 2); });
test('R2B3 preview 11 — consulta por data usa o índice', () => { const preview = createDoctoraliaPreview(payload, baseStore); assert.equal(getDoctoraliaPreviewSessionsForDate(preview, '2026-09-01').length, 1); });
test('R2B3 preview 12 — consulta por intervalo não devolve histórico fora da janela', () => { const preview = createDoctoraliaPreview(payload, baseStore); assert.equal(getDoctoraliaPreviewSessionsForRange(preview, '2026-09-01', '2026-09-01').length, 1); });
test('R2B3 preview 13 — consulta por paciente usa o índice', () => { const preview = createDoctoraliaPreview(payload, baseStore); const patientId = preview.store.patients.find(item => item.name.endsWith('A'))!.id; assert.equal(getDoctoraliaPreviewSessionsForPatient(preview, patientId).length, 2); });
test('R2B3 preview 14 — histórico desconhecido recebe rótulo administrativo', () => { const session = createDoctoraliaPreview(payload, baseStore).store.sessions.find(item => item.previewStatus === 'LEGACY_ATTENDANCE_UNKNOWN'); assert.equal(session?.administrativeNote, 'Histórico — comparecimento não informado'); });
test('R2B3 preview 15 — cancelado permanece cancelado', () => { const session = createDoctoraliaPreview(payload, baseStore).store.sessions.find(item => item.previewStatus === 'CANCELLED'); assert.equal(session?.status, 'cancelada'); });
test('R2B3 preview 16 — futuro permanece agendado', () => { const session = createDoctoraliaPreview(payload, baseStore).store.sessions.find(item => item.previewStatus === 'SCHEDULED'); assert.equal(session?.status, 'agendada'); });
test('R2B3 preview 17 — medicamentos ficam em background clínico protegido', () => { const preview = createDoctoraliaPreview(payload, baseStore); assert.equal(preview.bundle.clinicalBackgrounds[0]?.protected, true); assert.equal('medications' in preview.store.patients[0]!, false); });
test('R2B3 preview 18 — dados adicionais não entram no paciente administrativo', () => { const preview = createDoctoraliaPreview(payload, baseStore); assert.equal('address' in preview.store.patients[0]!, false); assert.equal(preview.patientDetailsById.size, 2); });
test('R2B3 preview 19 — catálogo de serviços e locais é preservado', () => { const preview = createDoctoraliaPreview(payload, baseStore); assert.equal(preview.store.services.length, 2); assert.equal(preview.store.locations.length, 1); });
test('R2B3 preview 20 — financeiro começa vazio', () => { const preview = createDoctoraliaPreview(payload, baseStore); assert.equal(preview.store.charges.length, 0); assert.equal(preview.store.payments.length, 0); assert.equal(preview.store.expenses.length, 0); });
test('R2B3 preview 21 — agenda pessoal do piloto é preservada', () => { const preview = createDoctoraliaPreview(payload, baseStore); assert.equal(preview.store.personalCommitments, baseStore.personalCommitments); });
test('R2B3 preview 22 — serialização não usa a chave normal do piloto', () => { const raw = serializeDoctoraliaPreviewBundle(createDoctoraliaPreviewBundle(payload, baseStore)); assert.equal(raw.includes('psychology-r1'), false); assert.equal(parseDoctoraliaPreviewBundle(raw)?.source, DOCTORALIA_PREVIEW_SOURCE); });
test('R2B3 preview 23 — payload inválido não reidrata', () => assert.equal(parseDoctoraliaPreviewBundle('{"version":2}'), null));
test('R2B3 preview 24 — endereço formatado exibe somente campos preenchidos', () => assert.deepEqual(formatDoctoraliaAddress({ street: 'Rua Fixture', number: '10', city: 'Cidade Teste', state: 'TS' }), ['Rua Fixture, 10', 'Cidade Teste - TS']));
test('R2B3 preview 25 — origem não altera dados persistidos', () => { const preview = createDoctoraliaPreview(payload, baseStore); assert.equal(preview.store.scope.professionalId, baseStore.scope.professionalId); assert.equal(preview.store.sessionRecords.length, 0); });

function localPatient(id: string, name: string, phone: string, externalReferences?: PsychologyPatient['externalReferences']): PsychologyPatient {
  return { id, professionalId: baseStore.scope.professionalId, context: 'PSICOLOGIA', name, birthDate: '1990-01-01', phone, preferredModality: 'presencial', active: true, createdAt: '2026-01-01T00:00:00.000Z', updatedAt: '2026-01-01T00:00:00.000Z', externalReferences };
}

function localStoreWithPatients(): PsychologyStore {
  const testOne = localPatient('test-fabiano', 'Fabiano', '(27) 99907-2659');
  const testTwo = localPatient('test-gertrudes', 'Gertrudes', '(27) 99999-9999');
  const other = localPatient('real-other', 'Paciente Local', '(27) 90000-0000');
  return { ...baseStore, patients: [testOne, testTwo, other], sessions: [
    { id: 'session-test', professionalId: baseStore.scope.professionalId, context: 'PSICOLOGIA', patientId: testOne.id, date: '2026-01-02', time: '09:00', durationMinutes: 50, modality: 'presencial', status: 'agendada', createdAt: '2026-01-01T00:00:00.000Z', updatedAt: '2026-01-01T00:00:00.000Z' },
    { id: 'session-other', professionalId: baseStore.scope.professionalId, context: 'PSICOLOGIA', patientId: other.id, date: '2026-01-03', time: '10:00', durationMinutes: 50, modality: 'presencial', status: 'agendada', createdAt: '2026-01-01T00:00:00.000Z', updatedAt: '2026-01-01T00:00:00.000Z' },
  ], sessionRecords: [{ id: 'record-test', patientId: testOne.id, sessionId: 'session-test', professionalId: baseStore.scope.professionalId, context: 'PSICOLOGIA', content: 'fixture', date: '2026-01-02', authorProfessionalId: baseStore.scope.professionalId, createdAt: '2026-01-02T00:00:00.000Z', updatedAt: '2026-01-02T00:00:00.000Z', sessionDate: '2026-01-02', sessionTime: '09:00' }], charges: [{ id: 'charge-test', patientId: testOne.id, sessionId: 'session-test', professionalId: baseStore.scope.professionalId, context: 'PSICOLOGIA', description: 'fixture', amount: 0, status: 'pending', createdAt: '2026-01-01T00:00:00.000Z', updatedAt: '2026-01-01T00:00:00.000Z' }], payments: [], sessionPackages: [], documents: [], attachments: [] };
}

test('R2B3 cleanup 26 — fingerprint normaliza telefone', () => assert.equal(normalizePsychologyPhone('(27) 99907-2659'), '27999072659'));
test('R2B3 cleanup 27 — paciente de teste pode ser excluído', () => { const store = localStoreWithPatients(); const result = deletePsychologyPatientLocally(store, 'test-fabiano'); assert.equal(result.removed, true); assert.equal(result.store.patients.some(patient => patient.id === 'test-fabiano'), false); });
test('R2B3 cleanup 28 — remove somente vínculos do paciente de teste', () => { const result = deletePsychologyPatientLocally(localStoreWithPatients(), 'test-fabiano'); assert.equal(result.store.sessions.some(session => session.id === 'session-test'), false); assert.equal(result.store.sessionRecords.some(record => record.id === 'record-test'), false); assert.equal(result.store.charges.some(charge => charge.id === 'charge-test'), false); assert.equal(result.store.sessions.some(session => session.id === 'session-other'), true); });
test('R2B3 cleanup 29 — outro paciente permanece', () => { const result = deletePsychologyPatientLocally(localStoreWithPatients(), 'test-fabiano'); assert.equal(result.store.patients.some(patient => patient.id === 'real-other'), true); });
test('R2B3 cleanup 30 — fingerprint divergente não impede exclusão definitiva', () => { const store = { ...localStoreWithPatients(), patients: [localPatient('test-fabiano', 'Fabiano', '(27) 99907-0000')] }; const result = deletePsychologyPatientLocally(store, 'test-fabiano'); assert.equal(result.removed, true); assert.equal(result.store.patients.length, 0); });
test('R2B3 cleanup 31 — referência Doctoralia não impede exclusão definitiva local', () => { const store = { ...localStoreWithPatients(), patients: [localPatient('doctoralia-fabiano', 'Fabiano', '(27) 99907-2659', [{ source: 'DOCTORALIA', externalId: 'external-1' }])] }; const result = deletePsychologyPatientLocally(store, 'doctoralia-fabiano'); assert.equal(result.removed, true); assert.equal(result.store.patients.length, 0); });
test('R2B3 cleanup 32 — paciente real com sessão pode sofrer hard-delete', () => { const store = { ...localStoreWithPatients(), patients: [localPatient('real-fabiano', 'Outra Pessoa', '(27) 99907-2659')], sessions: [{ ...localStoreWithPatients().sessions[0]!, patientId: 'real-fabiano' }] }; const assessment = getPsychologyPatientDeletionAssessment(store, 'real-fabiano'); assert.equal(assessment?.canDelete, true); assert.equal(assessment?.impact.sessions, 1); });
test('R2B3 cleanup 33 — paciente real com registro pode sofrer hard-delete', () => { const store = { ...localStoreWithPatients(), patients: [localPatient('real-fabiano', 'Outra Pessoa', '(27) 99907-2659')], sessionRecords: [{ ...localStoreWithPatients().sessionRecords[0]!, patientId: 'real-fabiano' }] }; assert.equal(getPsychologyPatientDeletionAssessment(store, 'real-fabiano')?.canDelete, true); });
test('R2B3 cleanup 34 — paciente real com financeiro pode sofrer hard-delete', () => { const store = { ...localStoreWithPatients(), patients: [localPatient('real-fabiano', 'Outra Pessoa', '(27) 99907-2659')], charges: [{ ...localStoreWithPatients().charges[0]!, patientId: 'real-fabiano' }] }; assert.equal(getPsychologyPatientDeletionAssessment(store, 'real-fabiano')?.canDelete, true); });
test('R2B3 cleanup 35 — paciente real com documento pode sofrer hard-delete', () => { const store = { ...localStoreWithPatients(), patients: [localPatient('real-fabiano', 'Outra Pessoa', '(27) 99907-2659')], documents: [{ id: 'document-real', professionalId: baseStore.scope.professionalId, context: 'PSICOLOGIA' as const, patientId: 'real-fabiano', category: 'Cadastro', classification: 'ADMINISTRATIVE' as const, filename: 'fixture.pdf', mimeType: 'application/pdf', createdAt: '2026-01-01T00:00:00.000Z', updatedAt: '2026-01-01T00:00:00.000Z' }] }; assert.equal(getPsychologyPatientDeletionAssessment(store, 'real-fabiano')?.canDelete, true); });
test('R2B3 cleanup 36 — impacto agregado é calculado para o modal', () => { const assessment = getPsychologyPatientDeletionAssessment(localStoreWithPatients(), 'test-fabiano'); assert.deepEqual(assessment?.impact, { sessions: 1, records: 1, charges: 1, payments: 0, expenses: 0, packages: 0, documents: 0, attachments: 0 }); });
test('R2B3 cleanup 37 — cancelamento de modal não altera store', () => { const store = localStoreWithPatients(); const before = JSON.stringify(store); assert.equal(JSON.stringify(store), before); });
test('R2B3 cleanup 38 — limpeza é puramente local e não possui chamada remota', () => { const result = deletePsychologyPatientLocally(localStoreWithPatients(), 'test-fabiano'); assert.equal(result.store.scope.context, 'PSICOLOGIA'); assert.equal(result.store.patients.some(patient => patient.externalReferences?.some(reference => reference.source === 'DOCTORALIA')), false); });
test('R2B3 cleanup 39 — inativação continua preservando registro', () => { const store = localStoreWithPatients(); const patient = store.patients.find(item => item.id === 'test-fabiano')!; const next = { ...store, patients: store.patients.map(item => item.id === patient.id ? { ...item, active: false } : item) }; assert.equal(next.patients.find(item => item.id === patient.id)?.active, false); assert.equal(next.sessions.some(session => session.patientId === patient.id), true); });
test('R2B3 cleanup 40 — avaliação inexistente não autoriza remoção', () => assert.equal(deletePsychologyPatientLocally(baseStore, 'missing').removed, false));

const agendaSource = readFileSync(new URL('../src/features/psychology-pilot/PsychologyPilot.tsx', import.meta.url), 'utf8');
test('R2B3 agenda compacta 41 — escala usa a janela clínica completa', () => assert.equal(getPsychologyAgendaScale(900, 1440).totalMinutes, PSYCHOLOGY_AGENDA_TOTAL_MINUTES));
test('R2B3 agenda compacta 42 — cartão de 50 minutos tem altura proporcional', () => { const scale = getPsychologyAgendaScale(900, 1440); assert.ok(scale.eventHeightForMinutes(50) > scale.minEventHeight); assert.ok(scale.eventHeightForMinutes(50) < scale.eventHeightForMinutes(90)); });
test('R2B3 agenda compacta 43 — cartão de 30 minutos é menor que o de 50', () => { const scale = getPsychologyAgendaScale(900, 1440); assert.ok(scale.eventHeightForMinutes(30) < scale.eventHeightForMinutes(50)); });
test('R2B3 agenda compacta 44 — cartão de 90 minutos é maior que o de 50', () => { const scale = getPsychologyAgendaScale(900, 1440); assert.ok(scale.eventHeightForMinutes(90) > scale.eventHeightForMinutes(50)); });
test('R2B3 agenda compacta 45 — horário preserva posição temporal', () => assert.equal(psychologyAgendaTimeToMinutes('18:30') - psychologyAgendaTimeToMinutes('07:00'), 690));
test('R2B3 agenda compacta 46 — intervalo de duas horas ocupa mais espaço que uma hora', () => { const scale = getPsychologyAgendaScale(900, 1440); assert.ok(scale.rowHeightForMinutes(120) > scale.rowHeightForMinutes(60)); });
test('R2B3 agenda confortável 47 — escala desktop de 1366×768 mantém 50 minutos legíveis', () => { const scale = getPsychologyAgendaScale(768, 1366); assert.ok(scale.pixelsPerMinute >= 1.2); assert.ok(scale.eventHeightForMinutes(50) >= 60); assert.ok(scale.eventHeightForMinutes(50) <= 75); });
test('R2B3 agenda confortável 48 — escala desktop de 1920×1080 mantém 50 minutos entre 60 e 75 px', () => { const scale = getPsychologyAgendaScale(1080, 1920); assert.ok(scale.eventHeightForMinutes(50) >= 60); assert.ok(scale.eventHeightForMinutes(50) <= 75); assert.ok(scale.minEventHeight >= 28); });
test('R2B3 agenda cards 49 — mobile mantém escala proporcional e linha tocável', () => { const scale = getPsychologyAgendaScale(768, 390); assert.ok(scale.minRowHeight >= 58); assert.equal(scale.eventHeightForMinutes(30), 36); assert.equal(scale.eventHeightForMinutes(50), 60); });
test('R2B3 agenda compacta 50 — intervalo inválido não quebra a escala', () => { const scale = getPsychologyAgendaScale(Number.NaN, Number.NaN); assert.ok(Number.isFinite(scale.rowHeightForMinutes(60))); });
test('R2B3 agenda cards 51 — simultâneos usam composição horizontal flexível', () => { assert.match(agendaSource, /relative z-10 flex flex-wrap items-start gap-1 overflow-visible/); assert.match(agendaSource, /simultaneous \? 'min-w-0 flex-1 basis-0'/); });
test('R2B3 agenda compacta 52 — o cartão semanal usa status compacto com tooltip completo', () => { assert.match(agendaSource, /StatusPill status=\{session\.status\} previewStatus=\{session\.previewStatus\} compact/); assert.match(agendaSource, /title=\{fullLabel\}/); });
test('R2B3 agenda compacta 53 — nomes longos são truncados sem alterar o nome acessível', () => { assert.match(agendaSource, /truncate text-\[11px\] font-black/); assert.match(agendaSource, /aria-label=\{`Abrir sessão de \$\{patientName\}`\}/); });
test('R2B3 agenda scroll 54 — a grade concentra rolagem vertical na área temporal', () => { assert.match(agendaSource, /overflow-x-auto rounded-3xl border border-slate-200 bg-white shadow-sm/); assert.match(agendaSource, /overflow-y-auto scroll-smooth/); assert.match(agendaSource, /data-testid=\{`psychology-agenda-scroll-\$\{mode\}`\}/); });
test('R2B3 agenda compacta 55 — data, duração e modalidade seguem no detalhe do cartão', () => { assert.match(agendaSource, /const title = `\$\{session\.time\} · \$\{patientName\} · Status:/); assert.match(agendaSource, /\$\{session\.durationMinutes\} min/); });
test('R2B3 agenda cards 56 — altura do card é duração vezes escala com box sizing real', () => { assert.match(agendaSource, /const height = Math\.max\(26, scale\.eventHeightForMinutes\(session\.durationMinutes\)\)/); assert.match(agendaSource, /height: `\$\{height\}px`/); assert.match(agendaSource, /boxSizing: 'border-box'/); assert.match(agendaSource, /flexShrink: 0/); assert.match(agendaSource, /rowHeightForMinutes\(Math\.max\(1, \(allTimes\[timeIndex \+ 1\]/); });
test('R2B3 agenda cards 57 — conteúdo do card permanece dentro do fundo colorido', () => { assert.match(agendaSource, /block shrink-0/); assert.match(agendaSource, /overflow-hidden rounded-lg/); assert.match(agendaSource, /truncate text-\[11px\] font-black/); });
test('R2B3 agenda cards 58 — simultâneos preservam altura e exibem detalhes quando há espaço', () => { assert.doesNotMatch(agendaSource, /\{!simultaneous && <div className=.*details/); assert.match(agendaSource, /bucket === 'full' && <div className=.*details/); assert.match(agendaSource, /const title = `\$\{session\.time\} · \$\{patientName\} · Status:/); });
test('R2B3 agenda corretiva 59 — banner Doctoralia ocupa uma única linha compacta', () => { assert.match(agendaSource, /somente local · não migrado/); assert.match(agendaSource, /px-4 py-1\.5 text-amber-950/); });
test('R2B3 agenda corretiva 60 — encerramento exige confirmação explícita', () => { assert.match(agendaSource, /previewEndConfirmation/); assert.match(agendaSource, /Encerrar prévia Doctoralia\?/); assert.match(agendaSource, /Os dados deixarão de aparecer temporariamente/); });
test('R2B3 agenda corretiva 61 — cancelar o modal não encerra a prévia', () => { assert.match(agendaSource, /onClick=\{\(\) => setPreviewEndConfirmation\(false\)\} className=\{secondaryButton\}>Cancelar/); });
test('R2B3 agenda corretiva 62 — reativação local automática continua disponível após recarregar', () => { assert.match(agendaSource, /fetch\('\/api\/psychology-doctoralia-preview'/); assert.match(agendaSource, /sessionStorage\.setItem\(DOCTORALIA_PREVIEW_STORAGE_KEY/); });
test('R2B3 agenda corretiva 63 — legenda evita repetição do nome padrão', () => { assert.match(agendaSource, /displayName !== baseLabel/); assert.match(agendaSource, /psychologyLegendLabel\(category, settings\)/); });
test('R2B3 agenda corretiva 64 — topo reduz ações duplicadas na página Agenda', () => { assert.match(agendaSource, /page !== 'agenda' && <button type="button" onClick=\{\(\) => openNewEvent\(\)\}/); assert.match(agendaSource, /className="mb-3 flex flex-col/); });
test('R2B3 agenda corretiva 65 — tipografia compacta mantém tamanhos mínimos definidos', () => { assert.match(agendaSource, /text-\[11px\] font-black/); assert.match(agendaSource, /text-\[10px\] font-bold/); assert.match(agendaSource, /text-\[9px\] leading-none/); });

const weeklyFixture = createPsychologyWeeklyAvailabilityFromLegacy([1], ['09:00', '10:00', '13:00', '14:00']);
test('R2B3 agenda horários 66 — legado vira dois períodos canônicos', () => { assert.deepEqual(getPsychologyAvailabilityPeriods({ weeklyAvailability: weeklyFixture }, 1), [{ startTime: '09:00', endTime: '11:00' }, { startTime: '13:00', endTime: '15:00' }]); });
test('R2B3 agenda horários 67 — períodos mantêm horários intermediários para a grade', () => { assert.deepEqual(getPsychologyAvailabilityTimes({ weeklyAvailability: weeklyFixture }), ['09:00', '10:00', '13:00', '14:00']); });
test('R2B3 agenda horários 68 — dia desabilitado não bloqueia os demais períodos', () => { assert.equal(isPsychologyDateTimeWithinAvailability({ weeklyAvailability: weeklyFixture }, '2026-01-05', '09:30'), true); assert.equal(isPsychologyDateTimeWithinAvailability({ weeklyAvailability: weeklyFixture }, '2026-01-06', '09:30'), false); });
test('R2B3 agenda horários 69 — intervalos inválidos são descartados na normalização', () => { const normalized = normalizePsychologyWeeklyAvailability([{ dayOfWeek: 1, enabled: true, periods: [{ startTime: '10:00', endTime: '09:00' }, { startTime: '09:00', endTime: '11:00' }] }], weeklyFixture); assert.deepEqual(getPsychologyAvailabilityPeriods({ weeklyAvailability: normalized }, 1), [{ startTime: '09:00', endTime: '11:00' }]); });
test('R2B3 agenda horários 70 — a ocupação usa os mesmos períodos canônicos', () => { const store = { ...baseStore, settings: { ...baseStore.settings, agenda: { ...baseStore.settings.agenda, weeklyAvailability: weeklyFixture } } }; const report = getPsychologyAgendaReport(store, { period: createPsychologyPeriod('custom', new Date('2026-01-05T12:00:00'), '2026-01-05', '2026-01-11'), sessionStatus: 'all', modality: 'all', patientStatus: 'all' }); assert.equal(report.availableMinutes, 240); assert.equal(report.availabilityConfigured, true); });
test('R2B3 agenda scroll 71 — cabeçalho dos dias fica sticky e existe retorno para Hoje', () => { assert.match(agendaSource, /sticky top-0 z-30/); assert.match(agendaSource, /onClick=\{onToday\}/); assert.match(agendaSource, />Hoje<\/button>/); });
test('R2B3 agenda scroll 72 — primeira posição considera sessão, disponibilidade ou fallback', () => { assert.match(agendaSource, /firstSession\?\.time \|\| getPsychologyFirstAvailabilityTime\(settings\.agenda\) \|\| '09:00'/); assert.match(agendaSource, /element\.scrollTop = scrollTop/); });
test('R2B3 agenda exceção 73 — horário fora da disponibilidade continua clicável e sinalizado', () => { assert.match(agendaSource, /onClick=\{\(\) => onNew\(date, time\)\}/); assert.match(agendaSource, /data-agenda-habitual=\{habitual \? 'true' : 'false'\}/); assert.match(agendaSource, /Fora da sua disponibilidade habitual/); });
test('R2B3 agenda exceção 74 — confirmação permite agendar mesmo assim', () => { assert.match(agendaSource, /psychology-outside-availability-warning/); assert.match(agendaSource, /Agendar mesmo assim/); assert.match(agendaSource, /isPsychologyDateTimeWithinAvailability\(settings\.agenda/); });
test('R2B3 agenda horários 75 — configurações expõem sete dias, múltiplos períodos e cópia semanal', () => { assert.match(agendaSource, /data-testid="psychology-availability-settings"/); assert.match(agendaSource, /Atendo neste dia/); assert.match(agendaSource, /Adicionar período/); assert.match(agendaSource, /Aplicar segunda a sexta/); });
test('R2B3 agenda horários 76 — sobreposição é normalizada em uma faixa contínua', () => { const normalized = normalizePsychologyWeeklyAvailability([{ dayOfWeek: 1, enabled: true, periods: [{ startTime: '09:00', endTime: '12:00' }, { startTime: '11:00', endTime: '14:00' }] }], weeklyFixture); assert.deepEqual(getPsychologyAvailabilityPeriods({ weeklyAvailability: normalized }, 1), [{ startTime: '09:00', endTime: '14:00' }]); });
test('R2B3 agenda horários 77 — contrato legado migra sem criar segunda fonte de verdade', () => { const settings = normalizePsychologySettings({ agenda: { workingDays: [1], availableTimes: ['09:00', '10:00'] } }, baseStore.scope); assert.deepEqual(settings.agenda.workingDays, [1]); assert.deepEqual(settings.agenda.availableTimes, ['09:00', '10:00']); assert.deepEqual(getPsychologyAvailabilityPeriods(settings.agenda, 1), [{ startTime: '09:00', endTime: '11:00' }]); assert.equal(getPsychologyAvailabilityPeriods(settings.agenda, 2).length, 0); });
test('R2B3 agenda cards 78 — buckets FULL COMPACT MINIMAL não renderizam linha parcial', () => { assert.match(agendaSource, /function psychologyAgendaCardBucket\(height: number\)/); assert.match(agendaSource, /if \(height >= 56\) return 'full'/); assert.match(agendaSource, /if \(height >= 36\) return 'compact'/); assert.match(agendaSource, /return 'minimal'/); assert.match(agendaSource, /bucket === 'minimal'/); assert.match(agendaSource, /bucket === 'full'/); });
test('R2B3 agenda cards 79 — 50 minutos usa FULL e 30 minutos usa COMPACT na escala final', () => { const scale = getPsychologyAgendaScale(900, 1440); assert.equal(scale.eventHeightForMinutes(50), 65); assert.equal(scale.eventHeightForMinutes(30), 39); assert.match(agendaSource, /data-agenda-bucket=\{bucket\}/); });
test('R2B3 agenda cards 80 — card que atravessa linhas temporais permanece acima do grid seguinte', () => { assert.match(agendaSource, /relative z-10 flex flex-wrap items-start gap-1 overflow-visible/); assert.match(agendaSource, /relative z-20/); assert.match(agendaSource, /block shrink-0/); });
test('R2B3 agenda cards 81 — scroll inicial deixa o primeiro evento abaixo do cabeçalho', () => { assert.match(agendaSource, /const scrollTop = Math\.max\(0, \(targetMinutes - startMinutes\) \* agendaScale\.pixelsPerMinute - agendaScale\.rowHeightForMinutes\(30\)\)/); assert.doesNotMatch(agendaSource, /rowHeightForMinutes\(60\) \/ 2/); });
test('R2B3 agenda cards 82 — tooltip mantém modalidade e duração mesmo nos buckets compactos', () => { assert.match(agendaSource, /const title = `\$\{session\.time\} · \$\{patientName\} · Status:/); assert.match(agendaSource, /title=\{`\$\{commitment\.time\} · \$\{title\} · \$\{details\}`\}/); });
test('R2B3 semântica 83 — cancelada usa fundo neutro, borda pastel e risco discreto', () => { const style = resolvePsychologyAgendaEventStyle({ source: 'SESSION', colors: baseStore.settings.colors, modality: 'online', serviceName: 'Consulta Psicologia', cancelled: true }); const tokens = derivePsychologyAgendaColorTokens(baseStore.settings.colors.ONLINE); assert.equal(style.backgroundColor, '#FFFFFF'); assert.equal(style.borderColor, tokens.softBorder); assert.equal(style.textColor, tokens.strongText); assert.equal(style.cancelled, true); assert.match(agendaSource, /data-agenda-cancelled=\{style\.cancelled \? 'true' : 'false'\}/); assert.match(agendaSource, /line-through decoration-1/); });
test('R2B3 semântica 84 — Terapia de Casal prioriza amarelo pastel em presencial e online', () => { const presencial = resolvePsychologyAgendaEventStyle({ source: 'SESSION', colors: baseStore.settings.colors, modality: 'presencial', location: baseStore.settings.locations[0], serviceName: 'Terapia de Casal' }); const online = resolvePsychologyAgendaEventStyle({ source: 'SESSION', colors: baseStore.settings.colors, modality: 'online', serviceName: 'Terapia de Casal Online' }); const cancelled = resolvePsychologyAgendaEventStyle({ source: 'SESSION', colors: baseStore.settings.colors, modality: 'online', serviceName: 'Terapia de Casal', cancelled: true }); const tokens = derivePsychologyAgendaColorTokens('#EAB308'); assert.equal(presencial.baseColor, '#EAB308'); assert.equal(online.baseColor, '#EAB308'); assert.equal(presencial.backgroundColor, tokens.softBackground); assert.equal(online.backgroundColor, tokens.softBackground); assert.equal(cancelled.backgroundColor, '#FFFFFF'); assert.equal(cancelled.borderColor, tokens.softBorder); assert.match(agendaSource, /data-agenda-service=\{serviceName \|\| ''\}/); });
test('R2B3 semântica 85 — Agenda Pessoal usa laranja e Mentoria permanece roxa em pastel', () => { const personal = resolvePsychologyAgendaEventStyle({ source: 'PERSONAL_AGENDA', colors: baseStore.settings.colors }); const mentoring = resolvePsychologyAgendaEventStyle({ source: 'MENTORING', colors: baseStore.settings.colors }); assert.equal(personal.baseColor, '#F97316'); assert.notEqual(personal.backgroundColor, personal.baseColor); assert.equal(mentoring.baseColor, baseStore.settings.colors.MENTORING); assert.notEqual(mentoring.backgroundColor, mentoring.baseColor); assert.match(agendaSource, /data-agenda-source="PERSONAL_AGENDA"/); });
test('R2B3 semântica 86 — remoção da prévia usa namespace reversível sem alterar o bundle', () => { const serialized = serializeDoctoraliaPreviewHiddenCancelledEventIds(['event-1', 'event-1', 'event-2']); assert.deepEqual(parseDoctoraliaPreviewHiddenCancelledEventIds(serialized), ['event-1', 'event-2']); assert.match(DOCTORALIA_PREVIEW_HIDDEN_CANCELLED_STORAGE_KEY, /:hidden-cancelled$/); assert.match(agendaSource, /Remover consulta cancelada da Agenda\?/); assert.match(agendaSource, /Ela será apenas ocultada desta prévia/); assert.match(agendaSource, /Restaurar consultas canceladas ocultadas/); });
test('R2B3 semântica 87 — lixeira é contextual no desktop e acessível ao toque', () => { assert.match(agendaSource, /aria-label="Remover consulta cancelada"/); assert.match(agendaSource, /sm:opacity-0 sm:group-hover:opacity-100/); assert.match(agendaSource, /onRemoveCancelled\(\)/); });
test('R2B3 pastel 88 — cada cor-base deriva fundo, borda e chip sem opacidade no card', () => { const tokens = derivePsychologyAgendaColorTokens('#2563EB'); assert.notEqual(tokens.softBackground, tokens.baseColor); assert.notEqual(tokens.softBorder, tokens.baseColor); assert.deepEqual(tokens.chipStyle, { backgroundColor: tokens.softBackground, borderColor: tokens.softBorder, color: tokens.strongText }); assert.match(agendaSource, /backgroundColor: style\.backgroundColor/); assert.doesNotMatch(agendaSource, /opacity:\s*0\.\d/); });
test('R2B3 pastel 89 — texto derivado mantém contraste legível inclusive no amarelo', () => { const yellow = derivePsychologyAgendaColorTokens('#EAB308'); const custom = derivePsychologyAgendaColorTokens('#D946EF'); assert.equal(hasReadableContrast(yellow.strongText), true); assert.equal(hasReadableContrast(custom.strongText), true); assert.notEqual(yellow.strongText, '#EAB308'); assert.notEqual(yellow.strongText, yellow.softBackground); });
test('R2B3 pastel 90 — customização mantém derivação previsível e sem fundo fixo por categoria', () => { const first = derivePsychologyAgendaColorTokens('#0EA5E9'); const second = derivePsychologyAgendaColorTokens('#0EA5E9'); const changed = derivePsychologyAgendaColorTokens('#14B8A6'); assert.deepEqual(first, second); assert.notEqual(first.softBackground, changed.softBackground); assert.notEqual(first.softBorder, changed.softBorder); });
test('R2B3 pastel 91 — Pessoal da legenda continua azul e agenda pessoal continua laranja', () => { const category = resolvePsychologyAgendaEventStyle({ source: 'SESSION', category: 'PERSONAL', colors: baseStore.settings.colors, modality: 'presencial' }); const personalAgenda = resolvePsychologyAgendaEventStyle({ source: 'PERSONAL_AGENDA', colors: baseStore.settings.colors }); assert.equal(category.baseColor, baseStore.settings.colors.PERSONAL); assert.equal(personalAgenda.baseColor, '#F97316'); assert.match(agendaSource, /agendaCategoryVisualStyle\(category, settings\)/); });
test('R2B3 pastel 92 — legenda e prévia de Ajustes usam os tokens do resolver', () => { assert.match(agendaSource, /backgroundColor: style\.backgroundColor, borderColor: style\.borderColor, color: style\.textColor/); assert.match(agendaSource, /data-testid="psychology-color-preview"/); assert.match(agendaSource, /Prévia suave na Agenda/); });
