import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import test from 'node:test';

const root = process.cwd();
const read = file => fs.readFileSync(path.join(root, file), 'utf8');
const harnessRoot = 'D:/Downloads/TESTE-MANUAL-WHATSAPP-R2I2-PAINEL-REAL';
const readHarness = file => fs.readFileSync(path.join(harnessRoot, file), 'utf8');
const app = read('src/App.tsx');
const sidebar = read('src/components/Navigation/SidebarNavigation.tsx');
const clinicalHeader = read('src/components/Navigation/ClinicalHeader.tsx');
const clinicalShell = read('src/components/Navigation/ClinicalAppShell.tsx');
const shell = read('src/features/whatsapp-simulation/components/SimulationShell.tsx');
const header = read('src/features/whatsapp-simulation/components/SimulationHeader.tsx');
const navigation = read('src/features/whatsapp-simulation/components/SimulationNavigation.tsx');
const simple = read('src/features/whatsapp-simulation/components/SimpleSimulationView.tsx');
const main = readHarness('main.tsx');
const css = readHarness('source-styles.css');
const config = readHarness('vite.config.mjs');
const nativeUi = `${clinicalHeader}\n${clinicalShell}\n${main}\n${css}\n${shell}\n${header}\n${navigation}\n${simple}`;

test('01 harness usa o ClinicalAppShell compartilhado', () => assert.match(main, /from ['"]@repo\/src\/components\/Navigation\/ClinicalAppShell/));
test('02 harness usa SidebarNavigation real', () => assert.match(main, /from ['"]@repo\/src\/components\/Navigation\/SidebarNavigation/));
test('03 harness usa o container app-main real', () => assert.match(clinicalShell, /app-main flex-1 w-full mx-auto/));
test('04 harness usa o CSS de tema real', () => assert.match(css, /@repo\/src\/index\.css/));
test('05 harness não importa App.tsx', () => assert.doesNotMatch(main, /App\.tsx|from ['"].*\/App/));
test('06 harness não importa Firebase ou serviços clínicos', () => assert.doesNotMatch(main + config, /firebase|firestore|server\.js|scheduler|watchdog|pm2|Meta|whatsapp-web/i));
test('07 host e porta são locais e estritos', () => assert.match(config, /host: '127\.0\.0\.1'|host: "127\.0\.0\.1"/));
test('08 perfil não aparece como seletor visual', () => assert.doesNotMatch(main, /Perfil sintético|Admin.*Profissional|Responsável.*Monitoramento/i));
test('09 tema não aparece como seletor visual', () => assert.doesNotMatch(main, /TEMA DO SISTEMA|Calm & Tech|Saúde & Equilíbrio|Acolhimento Suave/));
test('10 texto técnico fica fora da interface capturada', () => assert.match(main, /r2i2-technical-config/));
test('11 o shell real fornece o título da rota', () => assert.match(main, /activeLabel=\{canAccess \? 'WhatsApp'/));
test('12 o cabeçalho interno não duplica o título da rota', () => assert.doesNotMatch(header, />WhatsApp<|Gerencie mensagens, agendamentos e modelos de comunicação/));
test('13 alerta compacto usa linguagem de demonstração', () => assert.match(shell, /Ambiente de demonstração — nenhuma mensagem será enviada/));
test('14 navegação interna permanece com quatro áreas', () => {
  assert.equal((navigation.match(/label: '/g) || []).length, 4);
  assert.match(navigation, /overflow-x-auto/);
});
test('15 navegação interna usa padrão de abas do sistema', () => assert.match(navigation, /border-b border-clinic-primary|border-clinic-border/));
test('16 cartões usam clinic-card e tokens nativos', () => assert.match(simple, /clinic-card|shadow-clinic/));
test('17 campos usam clinic-input ou tokens equivalentes', () => assert.match(simple, /clinic-input|border-clinic-border-dark/));
test('18 agendamentos separam metadados com labels', () => assert.match(simple, /Telefone[\s\S]*Data[\s\S]*Horário/));
test('19 status de agendamento é chip', () => assert.match(simple, /rounded-full border px-2\.5 py-1/));
test('20 ações de agendamento ficam contidas e responsivas', () => assert.match(simple, /flex flex-wrap gap-2 sm:justify-end/));
test('21 layout usa os cartões e o ritmo vertical reais', () => { assert.match(shell, /clinic-card/); assert.match(shell, /gap-6 pb-24/); });
test('22 sidebar real mantém 320 e 76 pixels', () => assert.match(sidebar, /w-\[320px\].*w-\[76px\]|w-\[76px\].*w-\[320px\]/s));
test('23 permissões de produção permanecem Admin e Profissional', () => assert.match(app, /canAccessWhatsappSimulation[\s\S]*role === 'admin'[\s\S]*role === 'professional'/));
test('24 Responsável e Monitoramento continuam sem WhatsApp', () => assert.doesNotMatch(/const canAccessWhatsappSimulation[\s\S]*?;/.exec(app)?.[0] || '', /responsible|monitoring/i));
test('25 temas seguem mecanismo real por data-theme', () => assert.match(main + clinicalHeader, /applyTheme|data-theme|AppTheme/));
test('26 dados seguem sintéticos', () => assert.match(main, /demonstracao\.local|data-testid="r2i1-technical-config"/));
test('27 rede externa é bloqueada e encerra o harness', () => assert.match(main, /stopForExternal|connect-src|MutationObserver/));
test('28 persistência é bloqueada', () => assert.match(main, /Storage\.prototype|Persistência bloqueada/));
test('29 cores independentes do WhatsApp não aparecem', () => assert.doesNotMatch(nativeUi, /#25D366|#128C7E|#075E54|whatsapp-green/i));
test('30 lógica R2-S continua no domínio existente', () => assert.match(read('src/features/whatsapp-simulation/SimulationDashboard.tsx'), /createSimulationProvider|createInitialSimulationState/));
