import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import test from 'node:test';

const root = process.cwd();
const read = file => fs.readFileSync(path.join(root, file), 'utf8');
const harnessRoot = 'D:/Downloads/TESTE-MANUAL-WHATSAPP-R2I2-PAINEL-REAL';
const readHarness = file => fs.readFileSync(path.join(harnessRoot, file), 'utf8');
const app = read('src/App.tsx');
const shell = read('src/components/Navigation/ClinicalAppShell.tsx');
const header = read('src/features/whatsapp-simulation/components/SimulationHeader.tsx');
const navigation = read('src/features/whatsapp-simulation/components/SimulationNavigation.tsx');
const simulationShell = read('src/features/whatsapp-simulation/components/SimulationShell.tsx');
const simple = read('src/features/whatsapp-simulation/components/SimpleSimulationView.tsx');
const modal = read('src/components/Common/Modal.tsx');
const main = readHarness('main.tsx');
const css = readHarness('source-styles.css');
const config = readHarness('vite.config.mjs');
const activeUi = `${shell}\n${header}\n${navigation}\n${simulationShell}\n${simple}`;

test('01 shell visual compartilhado existe', () => assert.match(shell, /SidebarNavigation|ClinicalHeader/));
test('02 shell reutiliza a sidebar real', () => assert.match(shell, /from ['"]\.\/SidebarNavigation/));
test('03 shell reutiliza o cabeçalho real', () => assert.match(shell, /from ['"]\.\/ClinicalHeader/));
test('04 shell usa o container real', () => assert.match(shell, /app-main flex-1 w-full mx-auto/));
test('05 harness usa ClinicalAppShell', () => assert.match(main, /ClinicalAppShell/));
test('06 harness não importa App', () => assert.doesNotMatch(main, /App\.tsx|from ['"].*\/App/));
test('07 título WhatsApp é fornecido pela barra superior', () => assert.match(main, /activeLabel=\{canAccess \? 'WhatsApp'/));
test('08 cabeçalho interno não cria título WhatsApp duplicado', () => assert.doesNotMatch(header, /<h2[^>]*>WhatsApp<|Gerencie mensagens, agendamentos/));
test('09 seletor de perfil não é renderizado', () => assert.doesNotMatch(main, /select.*role|Perfil.*Admin|Trocar perfil/i));
test('10 seletor de tema não é renderizado', () => assert.doesNotMatch(main, /Calm & Tech|Acolhimento Suave|Saúde & Equilíbrio/));
test('11 selo técnico não é renderizado', () => assert.match(main, /r2i2-technical-config/));
test('12 conexão é o primeiro cartão nativo', () => assert.match(header, /clinic-card|simple-simulation-connection/));
test('13 conexão possui status em badge', () => assert.match(header, /rounded-full[\s\S]*Conectado/));
test('14 conexão possui ações simuladas', () => assert.match(header, /Conectar meu WhatsApp|Reconectar|Desconectar/));
test('15 reiniciar é ação secundária', () => assert.match(header, /border-t border-clinic-border[\s\S]*Reiniciar demonstração/));
test('16 segundo cartão possui título correto', () => assert.match(simulationShell, /Mensagens e agendamentos/));
test('17 segundo cartão possui descrição correta', () => assert.match(simulationShell, /Crie, agende e acompanhe mensagens/));
test('18 aviso aparece uma única vez no shell', () => assert.equal((simulationShell.match(/Ambiente de demonstração — nenhuma mensagem será enviada/g) || []).length, 1));
test('19 navegação interna possui quatro abas', () => assert.equal((navigation.match(/label: '/g) || []).length, 4));
test('20 navegação usa Agendadas', () => assert.match(navigation, /label: 'Agendadas'/));
test('21 navegação usa padrão de abas com borda', () => assert.match(navigation, /border-b-2 border-clinic-primary/));
test('22 navegação possui estado ativo acessível', () => assert.match(navigation, /aria-current/));
test('23 mensagem nova possui assistente de quatro etapas', () => assert.match(simple, /Etapa \{step\} de 4/));
test('24 indicador possui barra de progresso acessível', () => assert.match(simple, /role="progressbar"/));
test('25 somente a etapa atual é renderizada', () => assert.match(simple, /step === 1[\s\S]*step === 2[\s\S]*step === 3[\s\S]*step === 4/));
test('26 etapa 1 exige responsável', () => assert.match(simple, /Selecionar responsável[\s\S]*simple-recipient/));
test('27 etapa 1 mostra apenas telefone mascarado', () => assert.match(simple, /Telefone • final/));
test('28 etapa 2 oferece mensagem pronta', () => assert.match(simple, /Usar uma mensagem pronta/));
test('29 etapa 2 oferece mensagem manual', () => assert.match(simple, /Escrever uma nova mensagem/));
test('30 opções de mensagem são controles', () => assert.match(simple, /aria-pressed=\{messageMode ===/));
test('31 opção selecionada possui estado visual', () => assert.match(simple, /border-2 border-clinic-primary bg-clinic-primary\/5/));
test('32 textarea depende da escolha', () => assert.match(simple, /messageMode && \(messageMode === 'manual'/));
test('33 mensagem pronta mostra lista e seleção', () => assert.match(simple, /Mensagens prontas disponíveis[\s\S]*Selecionar/));
test('34 mensagem pronta mostra prévia natural', () => assert.match(simple, /resolveTemplatePreview\(template\.content\)/));
test('35 mensagem manual usa clinic-input', () => assert.match(simple, /simple-message-content[\s\S]*clinic-input/));
test('36 etapa 3 oferece Enviar agora', () => assert.match(simple, /Enviar agora/));
test('37 etapa 3 oferece Agendar', () => assert.match(simple, /Agendar para outro momento/));
test('38 etapa 3 exibe data apenas em agendamento', () => assert.match(simple, /when === 'scheduled' &&[\s\S]*type="date"/));
test('39 etapa 3 bloqueia data passada', () => assert.match(simple, /min=\{minimumDate\}/));
test('40 etapa 4 separa destinatário', () => assert.match(simple, /Destinatário/));
test('41 etapa 4 separa telefone', () => assert.match(simple, /Telefone/));
test('42 etapa 4 separa mensagem', () => assert.match(simple, /Mensagem/));
test('43 etapa 4 separa envio', () => assert.match(simple, /Envio/));
test('44 etapa 4 separa data e horário', () => assert.match(simple, /Data e horário/));
test('45 ações da conferência usam rodapé', () => assert.match(simple, /<footer className="flex flex-col-reverse/));
test('46 ações não usam posicionamento absoluto', () => assert.doesNotMatch(simple, /absolute[^\n]*(Confirmar|Continuar|Voltar)/));
test('47 cartões agendados usam clinic-card', () => assert.match(simple, /simple-scheduled-card[\s\S]*clinic-card/));
test('48 cartões agendados possuem badge de status', () => assert.match(simple, /statusClasses\(schedule\.status\)/));
test('49 cartões agendados separam metadados', () => assert.match(simple, /Telefone[\s\S]*Data[\s\S]*Horário/));
test('50 ações agendadas ficam contidas', () => assert.match(simple, /flex flex-wrap gap-2 sm:justify-end/));
test('51 Mensagens prontas mantém lista e formulário separados', () => assert.match(simple, /simple-ready-message-form[\s\S]*simple-ready-messages/));
test('52 Mensagens prontas não expõe códigos', () => assert.doesNotMatch(simple, /allowedVariables|sourceTemplateId|templateVersion|\{\{/));
test('53 módulo usa Modal real', () => assert.match(header, /from ['"]\.\.\/\.\.\/\.\.\/components\/Common\/Modal/));
test('54 modal possui descrição associada', () => assert.match(header, /descriptionId="simulation-dialog-description"/));
test('55 modal recebe foco inicial em Cancelar', () => assert.match(header, /initialFocusRef=\{cancelRef\}/));
test('56 modal real suporta Escape e foco contido', () => { assert.match(modal, /event\.key === 'Escape'/); assert.match(modal, /event\.key !== 'Tab'/); });
test('57 tema verde permanece disponível', () => assert.match(activeUi + read('src/index.css'), /health-balance/));
test('58 tema azul permanece disponível', () => assert.match(activeUi + read('src/index.css'), /calm-tech/));
test('59 tema nude permanece disponível', () => assert.match(activeUi + read('src/index.css'), /soft-welcome/));
test('60 permissões continuam restritas a admin e profissional', () => assert.match(app, /canAccessWhatsappSimulation[\s\S]*role === 'admin'[\s\S]*role === 'professional'/));
test('61 dados do harness são sintéticos', () => assert.match(main, /demonstracao\.local|data:image\/svg/));
test('62 rede do harness é bloqueada', () => assert.match(main + readHarness('index.html'), /stopForExternal|connect-src|MutationObserver/));
test('63 persistência do harness é bloqueada', () => assert.match(main, /Storage\.prototype|Persistência bloqueada/));
test('64 harness é local e sem Firebase/Meta/robô', () => { assert.match(config, /host: '127\.0\.0\.1'/); assert.doesNotMatch(main + config, /firebase|Meta|scheduler|watchdog|pm2|whatsapp-web/i); });
