import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import test from 'node:test';

const root = process.cwd();
const featureRoot = path.join(root, 'src', 'features', 'whatsapp-simulation');
const uiFiles = [
  'SimulationDashboard.tsx',
  path.join('components', 'SimulationHeader.tsx'),
  path.join('components', 'SimulationNavigation.tsx'),
  path.join('components', 'SimpleSimulationView.tsx'),
].map(file => path.join(featureRoot, file));
const ui = uiFiles.map(file => fs.readFileSync(file, 'utf8')).join('\n');
const coreFiles = fs.readdirSync(featureRoot, { recursive: true }).filter(file => /\.(ts|tsx|js)$/.test(file)).map(file => path.join(featureRoot, file));
const core = coreFiles.map(file => fs.readFileSync(file, 'utf8')).join('\n');
const navigation = fs.readFileSync(path.join(featureRoot, 'components', 'SimulationNavigation.tsx'), 'utf8');
const header = fs.readFileSync(path.join(featureRoot, 'components', 'SimulationHeader.tsx'), 'utf8');
const simple = fs.readFileSync(path.join(featureRoot, 'components', 'SimpleSimulationView.tsx'), 'utf8');
const commonModal = fs.readFileSync(path.join(root, 'src', 'components', 'Common', 'Modal.tsx'), 'utf8');
const dashboard = fs.readFileSync(path.join(featureRoot, 'SimulationDashboard.tsx'), 'utf8');
const stateStore = fs.readFileSync(path.join(featureRoot, 'state', 'simulationStore.ts'), 'utf8');
const actions = fs.readFileSync(path.join(featureRoot, 'state', 'simulationActions.ts'), 'utf8');
const scheduleActions = fs.readFileSync(path.join(featureRoot, 'state', 'simulationScheduleActions.ts'), 'utf8');
const presentation = fs.readFileSync(path.join(featureRoot, 'domain', 'templatePresentation.ts'), 'utf8');

test('01 existem somente quatro áreas visíveis', () => assert.equal((navigation.match(/label: '/g) || []).length, 4));
test('02 Nova mensagem é a área inicial', () => assert.match(stateStore, /activeView: 'new_message'/));
test('03 Meu WhatsApp está visível', () => assert.match(navigation, /Meu WhatsApp/));
test('04 Agendadas está visível', () => assert.match(navigation, /Agendadas/));
test('05 Mensagens prontas está visível', () => assert.match(navigation, /Mensagens prontas/));
test('06 Caixa de entrada não aparece na navegação', () => assert.doesNotMatch(navigation, /Caixa de entrada/));
test('07 Fila operacional não aparece na navegação', () => assert.doesNotMatch(navigation, /Fila operacional/));
test('08 relógio fictício não aparece na navegação', () => assert.doesNotMatch(navigation, /relógio|timezone|clock/i));
test('09 tenant não aparece na navegação', () => assert.doesNotMatch(navigation, /tenant/i));
test('10 seletor de perfis não aparece na navegação', () => assert.doesNotMatch(navigation, /perfil/i));
test('11 IDs técnicos não aparecem no texto da navegação', () => assert.doesNotMatch(navigation, /SIM-|id técnico|messageLogicalId/i));
test('12 estados técnicos em inglês não aparecem na navegação', () => assert.doesNotMatch(navigation, /scheduled|queued|pending|processing|completed|failed|expired/i));
test('13 conexão simulada funciona', () => assert.match(header, /onConnect\(\)|Conectar meu WhatsApp|Continuar simulação/));
test('14 conexão não utiliza rede', () => assert.doesNotMatch(ui, /fetch\s*\(|axios|XMLHttpRequest|WebSocket/));
test('15 desconexão simulada funciona', () => assert.match(header, /onDisconnect\(\)|Desconectar/));
test('16 reconexão simulada funciona', () => assert.match(header, /Reconectar/));
test('17 número exibido é sintético e mascarado', () => assert.match(simple, /Telefone • final/));
test('18 responsável pode ser selecionado', () => assert.match(simple, /simple-recipient|onSelectConversation/));
test('19 mensagem pronta pode ser escolhida', () => assert.match(simple, /Escolher mensagem pronta|onUseTemplate/));
test('20 mensagem pronta pode ser personalizada', () => assert.match(simple, /simple-message-content|onDraftChange/));
test('21 personalização não altera a mensagem original', () => assert.match(actions, /setSimulationComposition/));
test('22 mensagem manual funciona', () => assert.match(simple, /Escrever uma nova mensagem/));
test('23 opção Enviar agora funciona', () => assert.match(simple, /Enviar agora/));
test('24 opção Agendar funciona', () => assert.match(simple, /Agendar para outro momento/));
test('25 data passada é rejeitada', () => assert.match(scheduleActions, /scheduledAt.*state\.clock\.now/));
test('26 horário inválido é rejeitado', () => assert.match(scheduleActions, /isoDateTime/));
test('27 pré-visualização funciona', () => assert.match(simple, /Conferir mensagem|simple-message-preview/));
test('28 voltar e editar funciona', () => assert.match(simple, /Voltar e editar/));
test('29 cancelar prévia não registra', () => assert.match(dashboard, /onCancelPreview|preview: null/));
test('30 confirmação registra uma única vez', () => assert.match(actions, /registerPreviewedSimulatedMessage/));
test('31 repetição permanece idempotente', () => assert.match(core, /Operação repetida|idempotent/i));
test('32 mensagem agendada aparece na lista', () => assert.match(simple, /simple-scheduled-card|Mensagens agendadas/));
test('33 item agendado pode ser editado', () => assert.match(simple, /Editar mensagem|onEditSchedule/));
test('34 item agendado pode ser cancelado', () => assert.match(simple, /Deseja cancelar esta mensagem agendada|onCancelSchedule/));
test('35 item com falha apresenta Tentar novamente', () => assert.match(simple, /Tentar novamente/));
test('36 tentativa não exibe detalhes técnicos', () => assert.doesNotMatch(simple, /HTTP|stack trace|messageLogicalId|previousJobId|idempotencyKey/));
test('37 situações internas são traduzidas', () => assert.match(simple, /Concluída|Cancelada|Falhou|Agendada/));
test('38 mensagem pronta pode ser criada', () => assert.match(simple, /Criar mensagem pronta|onBeginTemplate/));
test('39 mensagem pronta pode ser editada', () => assert.match(simple, /Editar mensagem pronta|onEditTemplate/));
test('40 mensagem pronta pode ser ativada', () => assert.match(simple, /Ativar|onActivateTemplate/));
test('41 mensagem pronta pode ser desativada', () => assert.match(simple, /Desativar|onDeactivateTemplate/));
test('42 versões internas não aparecem', () => assert.doesNotMatch(simple, /templateVersion|sourceTemplateId|version/));
test('43 variáveis técnicas não aparecem', () => assert.doesNotMatch(simple, /allowedVariables|\{\{/));
test('44 reiniciar demonstração restaura fixtures', () => assert.match(header + dashboard, /Reiniciar demonstração|createInitialSimulationState/));
test('45 reload conceitual remove alterações', () => assert.match(stateStore, /createInitialSimulationState/));
test('46 interface utiliza português do Brasil', () => assert.match(ui, /WhatsApp|Mensagens|Conectar|Agendar/));
test('47 interface não contém termos técnicos proibidos nos rótulos principais', () => assert.doesNotMatch(navigation + header, /R2-[ABC]|Ambiente interno|timezone|WABA|webhook|access token/i));
test('48 R2-C continua funcionando internamente', () => assert.match(core, /SimulationQueueJob|advanceSimulationClock|processSimulationJob/));
test('49 R2-B continua funcionando internamente', () => assert.match(core, /quickReply|registerSyntheticInboundMessage/));
test('50 R2-A continua funcionando internamente', () => assert.match(core, /SimulationTemplate|selectVisibleTemplates/));
test('51 R1 continua funcionando', () => assert.match(core, /createSimulationProvider|registerMessage/));
test('52 isolamento por tenant permanece no domínio', () => assert.match(core, /assertActiveTenant|tenantId/));
test('53 permissões anteriores permanecem no domínio', () => assert.match(core, /assertSimulationPermission|permissionPolicy/));
test('54 fila interna permanece idempotente', () => assert.match(scheduleActions, /idempotencyKey|duplicate/));
test('55 nenhuma chamada fetch ocorre', () => assert.doesNotMatch(core, /\bfetch\s*\(/i));
test('56 axios não é utilizado', () => assert.doesNotMatch(core, /\baxios\b/i));
test('57 nenhuma persistência é utilizada', () => assert.doesNotMatch(core, /localStorage|sessionStorage|indexedDB|document\.cookie/i));
test('58 Firebase não é importado', () => assert.doesNotMatch(core, /firebase|firebase-admin/i));
test('59 Meta não é importada', () => assert.doesNotMatch(core, /Meta Cloud|Embedded Signup|meta-api/i));
test('60 robô não é importado', () => assert.doesNotMatch(core, /whatsapp-web\.js|server\.js|watchdog|OperationalReport/i));
test('61 App.tsx integra a R2-S sem reabrir a aplicação clínica completa', () => {
  const app = fs.readFileSync(path.join(root, 'src', 'App.tsx'), 'utf8');
  assert.match(app, /WhatsappSimulationDashboard/);
  assert.match(app, /activeTab === 'whatsapp'/);
  assert.doesNotMatch(app, /activeTab === 'whatsapp-simulacao'/);
});
test('62 arquivos proibidos não são referenciados pela nova camada visual', () => assert.doesNotMatch(ui, /from ['"].*(App\.tsx|Firebase|server\.js|scheduler|watchdog|Agenda|Reports)/i));
test('63 formulário não expõe chaves de composição', () => assert.doesNotMatch(simple, /\{\{\s*[a-zA-Z0-9_]+\s*\}\}|contato_nome|profissional_nome|data_ficticia|horario_ficticio/));
test('64 controles técnicos anteriores não aparecem', () => assert.doesNotMatch(simple, /Adicionar à mensagem|valor fictício|allowedVariables/));
test('65 nome da mensagem está presente', () => assert.match(simple, /Nome da mensagem/));
test('66 finalidade estruturada está presente', () => assert.match(simple, /Finalidade|Lembrete|Confirmação|Reagendamento|Aviso|Outro/));
test('67 texto principal está presente', () => assert.match(simple, /Texto principal|simple-template-body/));
test('68 personalização automática está presente', () => assert.match(simple, /Personalizar automaticamente/));
test('69 personalização do responsável funciona', () => assert.match(simple, /Usar o nome do responsável na saudação|useContactName/));
test('70 personalização de data e horário funciona', () => assert.match(simple, /Incluir a data e o horário|includeDateTime/));
test('71 personalização de assinatura funciona', () => assert.match(simple, /Assinar com o nome do profissional|signProfessional/));
test('72 prévia profissional é permanente e resolvida', () => assert.match(simple, /Como a mensagem ficará|simple-template-preview|resolveTemplatePreview/));
test('73 domínio preserva opções de apresentação', () => assert.match(presentation, /useContactName|includeDateTime|signProfessional/));
test('74 texto principal é preservado no formulário', () => assert.match(simple, /value=\{presentation\.body\}/));
test('75 botão de salvar é explícito', () => assert.match(simple, /Salvar mensagem pronta/));
test('76 lista fica oculta durante edição', () => assert.match(simple, /if \(templateDraft\)/));
test('77 lista retorna após salvar ou cancelar', () => assert.match(simple, /onSaveTemplate|onCancelTemplate/));
test('78 cartão mostra prévia resolvida', () => assert.match(simple, /const preview = props\.resolveTemplatePreview\(item\.content\)/));
test('79 Nova mensagem usa conteúdo resolvido', () => assert.match(simple, /resolveTemplatePreview\(template\.content\)/));
test('80 edição do compositor permanece independente', () => assert.match(actions, /setSimulationComposition/));
test('81 composição interna usa o domínio existente', () => assert.match(presentation, /composeTemplateContent|contato_nome|profissional_nome|data_ficticia|horario_ficticio/));
test('82 edição interpreta fixtures antigas', () => assert.match(presentation, /createTemplatePresentation|preserveLegacy|legacyContent/));
test('83 validação interna rejeita variável arbitrária', () => assert.match(core, /Variáveis não permitidas/));
test('84 mensagens técnicas não aparecem no editor', () => assert.doesNotMatch(simple, /\{\{\s*[a-zA-Z0-9_]+\s*\}\}|token|parser|sintaxe|marcador|processamento interno|propriedades técnicas/));
test('85 confirmação de reinício continua acessível', () => {
  assert.match(header, /Modal isOpen|descriptionId|initialFocusRef/);
  assert.match(commonModal, /role="dialog"|aria-modal/);
});
test('86 R2-S mantém a proteção de rede e persistência', () => assert.doesNotMatch(core, /\bfetch\s*\(|localStorage|sessionStorage|WebSocket|XMLHttpRequest/));
